FORMAT: 1A

# Cards Against Ocaml

This document specifies the APIs for Cards Against OCaml. The server for the game should implement these interfaces
exactly. Click on each to get more information about what the JSON should look like

Note that a common trend through all the API's is the requirement of a username parameter. If you fail to provide this
parameter then the API call will return a 401, except in the case of login. Login adds the user to the server for the
game.

A cards against humanity game is split into 

# Group Authentication
Relating to calls about authentication.
## Login [/user/login]
### Log in to the server [POST]
The user making this call will need to submit a username, through the request header, that they shall use for the game that they will join.

+ Request (application/json)
    + Header

        username: "acidic"

+ Response 200 (No Content)

## Quit [/user/quit]
### Quit out of the server [DELETE]
The user making this call will need to pass in the username that they wish to remove from the game.

+ Request (application/json)
    + Header

        username: "acidic"

+ Response 200 (No Content)

# Group Timing
Relating to calls about timing that are frequently made to the server
## Heartbeat [/time/heartbeat]
### Send a heartbeat [POST]

+ Request (No Content)

+ Response 200 (No Content)

## Timer [/time/timer]
### Get Round Timer [GET]

# Group Model
Relating to calls to get the current world state.
##



# Group Playing
Relating to calls that a non-card czar player would make during the play phase.


# Group Judging
Relating to calls that the card czar would be making




